name: generate
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version, ex: div, v0.0.1'
        type: string
        required: false
        default: dev

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: build
        run: |
          mkdir out

          zip -r __tmp README.md LICENSE location_marker mcdreforged.plugin.json
          mv __tmp.zip ../out/LocationMarker-CTEC-${{ inputs.releaseVersion }}.mcdr

      - uses: actions/upload-artifact@v3
        with:
          name: LocationMarker-CTEC-${{ inputs.releaseVersion }}
          path: out
